platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

def project_pods
  pod 'SwiftLint'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'

end

target 'Promesometro-iOS' do
  project_pods

  target 'Promesometro-iOSTests' do
    inherit! :search_paths
    project_pods
  end
end
