platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

def app_pods
  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
end

def ui_pods
  pod 'RAMAnimatedTabBarController'
end

def web_service_pods
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'
end

def shared_pods
  pod 'PromisedFuture'
end

target 'Promesometro-iOS' do
  app_pods
  ui_pods
  shared_pods
  #  target 'Promesometro-iOSTests' do
  #    inherit! :search_paths
  #    app_pods
  #  end
end

target 'PromesometroService' do
  web_service_pods
  shared_pods
end
